services:
  nginx:
    container_name: server
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/default.conf
      - ./.logs/nginx:/var/log/nginx
    networks:
      - backend

  php:
    depends_on:
      - nginx
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - /.docker/php/ini-files/php.ini-development:/usr/local/etc/php/php.ini-development
      - /.docker/php/ini-files/php.ini-production:/usr/local/etc/php/php.ini-production
    networks:
      - backend

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###


networks:
  backend: {}
