services:
  nginx:
    container_name: server
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend/:/var/www/html
      - ./backend/conf.d:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php:
    depends_on:
      - nginx
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /var/www/html
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./backend/:/var/www/html
    networks:
      - backend
      - public

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/public:/app/public
      - ./frontend/styles:/app/styles
    depends_on:
      - nginx
      - php
    networks:
      - public

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: app
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ./.data/db:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - backend
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###


networks:
  backend: {}
  public: {}