services:
  nginx:
    container_name: server
    image: nginx:1.23.2-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/default.conf
      - ./.logs/nginx:/var/log/nginx
    networks:
      - backend

  php:
    depends_on:
      - nginx
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/pgdata
    volumes:
      - ./.data/database:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - backend
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###


networks:
  backend: {}
